on:
  push:
    branches:
      - develop
      - master

name: Unit test and build

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '14', '16' ]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run test:ci
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    name: Build package
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: 14
      - run: npm ci
      - run: npm run build